export const GET_WORST_FILMS = 'GET_WORST_FILMS';
export const GET_MAIN_CAST_AND_CREW_OF_FILM = 'GET_MAIN_CAST_AND_CREW_OF_FILM';
export const GET_SCREEN_OF_FILM = 'GET_SCREEN_OF_FILM';
export const CHANGE_TEXT_OF_BUTTON_MORE_INF_BUTTON = 'CHANGE_TEXT_OF_BUTTON_MORE_INF_BUTTON';
export const CHANGE_DISPLAY_VALUE_OF_INF_BLOCK = 'CHANGE_DISPLAY_VALUE_OF_INF_BLOCK';